kind: Service
apiVersion: v1
metadata:
  name: burrow
  namespace: kafka
spec:
  selector:
    app: burrow
  ports:
  - name: web
    protocol: TCP
    port: 80
  - name: api
    protocol: TCP
    port: 8000
  - name: prometheus
    protocol: TCP
    port: 8080
