kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: kafka-zookeeper
  resources:
    requests:
      storage: 1Gi
