kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-broker
  labels:
    k8s-addon: storage-aws.addons.k8s.io
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp2
