apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv-simildon
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-broker
  local:
    path: /D/kubernetes-kafka-broker-mount-path <storage path>
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <node name e.g. node.machine.com >
